---
version: '3.7'

services:
  web:
    image: golang:1.11.1
    working_dir: /go/src/app
    volumes:
    - ./:/go/src/app
    ports:
    - 8080:8080
    links:
    - redis
    command: >
      sh -c "go get -d -t github.com/gomodule/redigo/redis &&  go get -d -t github.com/pkg/errors && go run main.go"

  redis:
    image: redis:5.0.0
    restart: always