---
version: '3.7'

services:
#  web:
#    image: golang:1.11.1
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: go run main.go
  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
    restart: always